language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - 7.1

before_script:
  - composer self-update
  - composer install
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod 777 ./phpunit.phar

script:
  - ./phpunit.phar
